exports.productsData = [
  {
    title: 'iPhone 15 Pro Max',
    description: 'iPhone 15 Pro Max',
    price: 1999,
    tags: ['iphone', 'apple', 'mobile'],
    category: ['iphone'],
    stock: 100,
    image: '/products/iphone/iphone-15-pro-max.jpg',
  },
  {
    title: 'iPhone 15 Pro',
    description: 'Apple iPhone 15 Pro',
    price: 999,
    tags: ['iphone', 'apple', 'smartphone'],
    category: ['iphone'],
    stock: 50,
    image: '/products/iphone/iphone15-pro.jpg',
  },
  {
    title: 'iPhone 15 Pro',
    description: 'Apple iPhone 15',
    price: 999,
    tags: ['iphone', 'apple', 'smartphone'],
    category: ['iphone'],
    stock: 50,
    image: '/products/iphone/iphone-15.jpg',
  },
  {
    title: 'Apple Watch Ultra',
    description: 'Apple Watch Ultra',
    price: 799,
    tags: ['watch', 'apple', 'wearable'],
    category: ['watch'],
    stock: 150,
    image: '/products/watch/watch-ultra.jpeg',
  },
  {
    title: 'Apple Watch Series 9',
    description: 'Apple Watch Series 9',
    price: 399,
    tags: ['watch', 'apple', 'wearable'],
    category: ['watch'],
    stock: 75,
    image: '/products/watch/series9.jpg',
  },
  {
    title: 'Apple Watch SE',
    description: 'Apple Watch SE',
    price: 399,
    tags: ['watch', 'apple', 'wearable'],
    category: ['watch'],
    stock: 75,
    image: '/products/watch/se.jpg',
  },
  {
    title: 'Apple Watch SE',
    description: 'Apple Watch SE',
    price: 279,
    tags: ['watch', 'apple', 'wearable'],
    category: ['watch'],
    stock: 50,
    image: '/products/watch/se.jpg',
  },
  {
    title: 'AirPods Max',
    description: 'Apple AirPods Max',
    price: 1299,
    tags: ['airpods', 'apple', 'audio'],
    category: ['airpods'],
    stock: 25,
    image: '/products/airpods/airpod-max.jpg',
  },
  {
    title: 'AirPods Pro',
    description: 'Apple AirPods Pro',
    price: 549,
    tags: ['airpods', 'apple', 'audio'],
    category: ['airpods'],
    stock: 25,
    image: '/products/airpods/airpods-pro.jpg',
  },
  {
    title: 'AirPods 2nd Gen',
    description: 'AirPods 2nd Gen',
    price: 549,
    tags: ['airpods', 'apple', 'audio'],
    category: ['airpods'],
    stock: 25,
    image: '/products/airpods/airpods.jpg',
  },
  {
    title: 'AirPods 3rd Gen',
    description: 'AirPods 3rd Gen',
    price: 549,
    tags: ['airpods', 'apple', 'audio'],
    category: ['airpods'],
    stock: 25,
    image: '/products/airpods/airpods-3rd.jpg',
  },
  {
    title: 'Macbook Pro',
    description: 'Apple Macbook Pro',
    price: 1699,
    tags: ['macbook', 'apple', 'desktop'],
    category: ['mac'],
    stock: 50,
    image: '/products/macbook/macbook-pro-13.jpeg',
  },
  {
    title: 'Macbook Air',
    description: 'Apple Macbook Air',
    price: 1699,
    tags: ['macbook', 'apple', 'desktop'],
    category: ['mac'],
    stock: 50,
    image: '/products/macbook/macbook-air.jpeg',
  },
  {
    title: 'iMac',
    description: 'Apple iMac',
    price: 2199,
    tags: ['imac', 'apple', 'desktop'],
    category: ['mac'],
    stock: 50,
    image: '/products/macbook/imac.jpg',
  },
];
